### GET ALL ORDERS
http://localhost:3001/api/orders

### CREATE AN ORDER
POST http://localhost:3001/api/orders
Content-Type: application/json

{
  "productName": "product name 10",
  "image": "https://moonstore.org/wp/wp-content/uploads/2017/06/wood-product-paceholder.jpg",
  "quantity": 1,
  "deliveryAddress": "Chua Lang, Ha Noi, Viet Nam",
  "customerName": "Nguyen Xuan Hieu",
  "phone": "0963558935",
  "email": "xhieu94@gmail.com"
}

### GET AN ORDER
GET http://localhost:3001/api/orders/2
Content-Type: application/json

### UPDATE AN ORDER
PATCH http://localhost:3001/api/orders/1
Content-Type: application/json

{
  "productName": "product name 1 Updated again",
  "image": "https://moonstore.org/wp/wp-content/uploads/2017/06/wood-product-paceholder.jpg",
  "quantity": 1,
  "deliveryAddress": "Chua Lang, Ha Noi, Viet Nam",
  "customerName": "Nguyen Xuan Hieu",
  "phone": "0963558935",
  "email": "xhieu94@gmail.com",
  "status": "confirmed"
}

################################ AUTHENICATION ################################
### LOGIN
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

### PROTECTED ROUTE
http://localhost:3001/api/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW4iLCJzdWIiOjEsImlhdCI6MTYyMzY0MzQ3NCwiZXhwIjoxNjIzNjQzNTM0fQ.RgV4_gZYnrBi1uxzcX_PrvS2IWN_xqqhrX6jXxcSvo
